name: Build and test mapping coverage

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: DEBUG

jobs:
  linux:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]    
        compiler:
          - { compiler: GNU, CC: gcc-11, CXX: g++-11 }

    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.9.1
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install requirements
      run: |
        sudo apt install build-essential manpages-dev software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update && sudo apt install ${{ matrix.compiler.CC }} ${{ matrix.compiler.CXX }}
        sudo apt install 
          libhts-dev 
          libjemalloc-dev
          libgsl-dev
          zlib1g-dev
          libhts-dev
          samtools
          bedtools

    - name: Build
      env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
      # Build your program with the given configuration
      run: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && cmake --build build -- 
      
    - name: Basic version test
      env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
      run: build/bin/mashmap -v

    - name: Test coverage
      env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
      run: |
        ASAN_OPTIONS=detect_leaks=1:symbolize=1 LSAN_OPTIONS=verbosity=0:log_threads=1 build/bin/mashmap \
          -r data/scerevisiae8.fa.gz
          -q data/scerevisiae8.fa.gz
          --pi 95 -n 1 -Y '#' 
          -o scerevisiae8.paf; 
        scripts/test.sh data/scerevisiae8.fa.gz.fai scerevisiae8.paf 0.92

